import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SiteHeader, ThemeProvider, Footer, SessionProvider } from "@/components";
import { getSession } from "@/lib/server/get-session";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
  weight: "700"
})

export const metadata: Metadata = {
  title: "Faux Stakes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${spaceGrotesk.variable} ${inter.variable} antialiased`}
      >
        <SessionProvider initialSession={session}>
          <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
            <SiteHeader />
            <div className="mx-auto max-w-xs md:max-w-xl min-h-lvh lg:max-w-4xl bg-background">
              {children}
            </div>
            <Footer />
          </ThemeProvider>
        </SessionProvider>
        <Toaster position={"top-center"} theme="dark" />
      </body>
    </html>
  );
}
