import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SiteHeader, Footer, SessionProvider } from "@/components";
import { getSession } from "@/lib/server/get-session";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Orakl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased`} data-product="platform">
        <SessionProvider initialSession={session}>
          <SiteHeader />
          <main className="min-h-[calc(100svh-4rem)]">{children}</main>
          <Footer />
        </SessionProvider>
        <Toaster position={"top-center"} richColors />
      </body>
    </html>
  );
}
